version: '3'

tasks:
  build:
    cmd: bun run build
    sources:
      - src/**
    generates:
      - dist/**
  
  test:
    cmd: bun test

  publish:
    deps:
      - test
      - build
    cmd: bun publish